# Generated by Django 3.1.2 on 2021-01-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('auteur', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now=True)),
                ('image', models.ImageField(upload_to='Images')),
                ('image0', models.ImageField(upload_to='Images')),
                ('image1', models.ImageField(upload_to='Images')),
                ('image2', models.ImageField(upload_to='Images')),
                ('paragraphe0', models.TextField(blank=True, null=True)),
                ('paragraphe1', models.TextField(blank=True, null=True)),
                ('paragraphe2', models.TextField(blank=True, null=True)),
                ('url0', models.URLField(blank=True, null=True)),
                ('url1', models.URLField(blank=True, null=True)),
                ('url2', models.URLField(blank=True, null=True)),
                ('url3', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'url3',
            },
        ),
    ]
